name: nativeconnect_example
description: "Demonstrates how to use the nativeconnect package."
# 'none' ensures this example app itself isn't accidentally published to pub.dev
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Standard Flutter SDK range

dependencies:
  flutter:
    sdk: flutter

  # Local link to your main package
  nativeconnect:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Latest stable lints for clean code
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true